name: Update GitHub Pages

on:
  push:
    branches: [master]

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    if: "! contains(github.event.head_commit.message, '[CI-SKIP]')"
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2.3.4
      - name: Setup Node.js
        uses: actions/setup-node@v2.1.4
      - name: Cache Node.js modules
        uses: actions/cache@v2.1.3
        with:
          path: ~/.cache/yarn
          key: ${{ runner.OS }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-node-
            ${{ runner.OS }}-    
      - name: Install dependencies
        run: yarn install
      - name: Build pages
        run: yarn run build
      - name: Deploy pages
        uses: peaceiris/actions-gh-pages@v3.7.3
        with:
          external_repository: Siroshun09/siroshun09.github.io
          personal_token: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./dist
          allow_empty_commit: true
